/*
 * OIDC ICT Userinfo Endpoint
 *
 * Endpoint for OpenID Connect's ID Certifcation Token endpoint for userinfo.
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	ict "ict/go"
	"log"
	"net/http"
	"os"
)

func main() {
	log.Printf("Starting Server...")

	// Load configuration
	log.Printf("Loading configuration...")
	ict.Initialize()

	router := ict.NewRouter()

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Configuration loaded")

	log.Printf("Running on port " + port)

	log.Fatal(http.ListenAndServe(":"+port, router))
}
