/*
 * OIDC IAT Userinfo Endpoint
 *
 * Endpoint for OpenID Connect's ID Assertion Token endpoint for userinfo.
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iat

import (
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
)

// Chi free Router
func NewRouter() (router *chi.Mux) {
	router = chi.NewRouter()
	router.Use(middleware.Logger)
	router.Post("/", GenIat)
	router.Options("/", IatOptions)
	return
}
