/*
 * OIDC IAT Userinfo Endpoint
 *
 * Endpoint for OpenID Connect's ID Assertion Token endpoint for userinfo.
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iat

import (
	"net/http"
)

// Gorilla free Router
func NewRouter() (router *http.ServeMux) {
	router = http.NewServeMux()
	router.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodPost:
			GenIat(w, r)
		case http.MethodOptions:
			IatOptions(w, r)
		}
	},
	)
	return
}

// type Route struct {
// 	Name        string
// 	Method      string
// 	Pattern     string
// 	HandlerFunc http.HandlerFunc
// }

// type Routes []Route

// func NewRouter() *mux.Router {
// 	router := mux.NewRouter().StrictSlash(true)
// 	for _, route := range routes {
// 		var handler http.Handler
// 		handler = route.HandlerFunc
// 		handler = Logger(handler, route.Name)

// 		router.
// 			Methods(route.Method).
// 			Path(route.Pattern).
// 			Name(route.Name).
// 			Handler(handler)
// 	}

// 	return router
// }

// var routes = Routes{
// 	Route{
// 		"GenIat",
// 		strings.ToUpper("Post"),
// 		"/",
// 		GenIat,
// 	},
// 	Route{
// 		"IatOptions",
// 		strings.ToUpper("Options"),
// 		"/",
// 		IatOptions,
// 	},
// }
